var GPhoto, request,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

request = superagent;

GPhoto = (function() {
  function GPhoto() {
    this.displaySettings = __bind(this.displaySettings, this);
    this.enumSettings = __bind(this.enumSettings, this);
    this.loadSettings = __bind(this.loadSettings, this);
    this.updateSettings = __bind(this.updateSettings, this);
  }

  GPhoto.prototype.startPreview = function(address) {
    $('#camera').attr('src', address.substring(address.length - 5, 0) + ':8080' + '/?action=stream');
  };

  GPhoto.prototype.stopPreview = function() {
    $('#camera').attr('src', '');
  };

  GPhoto.prototype.loadSettings = function(cb, address) {
    return request.get(address + '/api/settings', (function(_this) {
      return function(settings) {
        if (cb) {
          return cb(JSON.parse(settings.text), null, address);
        }
      };
    })(this));
  };

  GPhoto.prototype.enumSettings = function(settings, gui, address) {
    if (!gui) {
      gui = this.gui;
    }
    return $.each(settings, (function(_this) {
      return function(key, val) {
        var changeFn, foo, _ref;
        if ((_ref = val.type) === 'window' || _ref === 'section') {
          return _this.enumSettings(val.children, gui.addFolder(val.label), address);
        } else {
          foo = {};
          foo[val.label] = val.value;
          changeFn = function(newValue) {
            console.log(val.label + " changed to " + newValue);
            return request.put(address + "/api/settings/" + key, {
              newValue: newValue
            }, function(response) {
              return console.log(response);
            });
          };
          if (val.type === 'string') {
            return gui.add(foo, val.label).onChange(changeFn);
          } else if (val.type === 'toggle') {
            foo[val.label] = val.value !== 0;
            return gui.add(foo, val.label).onChange(function(newValue) {
              return request.put(address + "/api/settings/" + key, {
                newValue: (newValue ? 1 : 0)
              }, function(response) {
                return console.log(response);
              });
            });
          } else if (val.type === 'choice') {
            return gui.add(foo, val.label, val.choices).onChange(changeFn);
          } else if (val.type === 'range') {
            return gui.add(foo, val.label, val.min, val.max, val.step).onChange(changeFn);
          }
        }
      };
    })(this));
  };

  GPhoto.prototype.displaySettings = function (address) {
    var foo;
    if (!this.gui) {
      this.gui = new dat.GUI({autoPlace: false});
      $('#gui-ctn').append(this.gui.domElement);
    }
    foo = {
      'Start live preview': (function(_this) {
        return function() {
          return _this.startPreview(address);
        };
      })(this),
      'Take picture': (function(_this) {
        return function() {
          return request.get(address + '/api/shoot/jpeg', function(res) {
            console.log(res);
            if (res.text) {
              $('#camera').attr('src', address + res.text + '?' + new Date().getTime());
            }
          });
        };
      })(this)
    };
    this.gui.add(foo, 'Take picture');
    if(config.stream){
      this.gui.add(foo, 'Start live preview');
    }
    this.loadSettings(this.enumSettings, address);
  };

  GPhoto.prototype.updateSettings = function (settings, address) {
    this.enumSettings(JSON.parse(settings), this.gui, address);
  }

  return GPhoto;

})();

// ---
// generated by coffee-script 1.9.0
